### PR TITLE
PRE-3823: Update keystores for Merchant A and Merchant B

### PR DESCRIPTION
**Pull request by hkbuvik**
https://servicedesk.bankidnorge.no/jira/projects/PRE/queues/custom/18/PRE-3823

### CODE REVIEW

**Comment by hkbuvik** [comment]
The keys for Merchant A and Merchant B in the integration tests are expired, so the tests will fail. The new keys are valid for 4 years.

**Comment by sottos** [comment]
Hvorfor bruker vi samme orgnummer på MerchantA og MerchantB. Ser det var det fra før også, merkelig.

**Comment by hkbuvik** [comment]
@heikkih Neither me or @sottos have rights to merge this, do you?

**Comment by sottos** [comment]
Og det har ingenting å si at orgnumrene er like, bare merge @heikkih

**Pull request merged**
